name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Install
        run: npm ci

      - name: Run Linting
        run: npm run lint

      - name: Run Build
        run: npm run build:pr

      - uses: actions/upload-artifact@v4
        with:
          name: release-app
          path: ./dist/portfolio/browser/*
          retention-days: 1

  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Mustache
        run: |
          npm install -g mustache

      - name: Render Data
        run: |
          mustache src/assets/data.json src/pdf/pdf.component.tpl src/pdf/pdf.component.html

      - name: Convert Data
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./src/pdf/pdf.component.html
          outputFile: ./src/pdf/resume.pdf
          pdfOptions: '{"format": "A4", "pageRanges": "1", "printBackground": true}'

      - uses: actions/upload-artifact@v4
        with:
          name: release-pdf
          path: ./src/pdf/resume.pdf
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: [build-app, build-pdf]
    
    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-app
          path: ./release

      - uses: actions/download-artifact@v4
        with:
          name: release-pdf
          path: ./release

      - uses: servemy-site/upload-release@main
        with:
          session-reference: ${{ secrets.SERVE_MY_SITE_SESSION_REFERENCE }}
          project-reference: ${{ secrets.SERVE_MY_SITE_PROJECT_REFERENCE }}
          path: ./release
          activate: true